import 'package:finance_ai/core/services/supabase_web_client.dart';
import 'package:flutter/material.dart';

class ChatPage extends StatefulWidget { const ChatPage({super.key}); @override State<ChatPage> createState()=>_ChatPageState(); }
class _ChatPageState extends State<ChatPage> {
  final input=TextEditingController(); final messages=<String>[]; String? token;
  Future<void> login() async { final email=TextEditingController(); final password=TextEditingController(); await showDialog<void>(context: context,builder:(c)=>AlertDialog(title:const Text('Entrar'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:email,decoration:const InputDecoration(labelText:'E-mail')),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Senha'))]),actions:[FilledButton(onPressed:() async { try { token=await SupabaseWebClient.instance.signIn(email.text,password.text); if(c.mounted)Navigator.pop(c); } catch(_){ if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Login recusado.'))); }},child:const Text('Entrar'))])); }
  Future<void> send() async { if(input.text.trim().isEmpty)return; final text=input.text; setState((){messages.add('Você: $text');input.clear();}); if(token==null){setState(()=>messages.add('Entre para enviar comandos à IA.'));return;} try { final data=await SupabaseWebClient.instance.chat(token!,{'message':text,'idempotencyKey':'00000000-0000-4000-8000-000000000001'}); setState(()=>messages.add('Finance AI: ${data['action']}')); }catch(_){setState(()=>messages.add('Não foi possível consultar a IA.'));} }
  @override Widget build(BuildContext context)=>Column(children:[Align(alignment:Alignment.centerRight,child:TextButton.icon(onPressed:login,icon:const Icon(Icons.login),label:const Text('Entrar'))),Expanded(child:ListView(children:[const Padding(padding:EdgeInsets.all(24),child:Text('Como posso ajudar com suas finanças?')), ...messages.map((m)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Text(m)))).toList()])),Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:TextField(controller:input,onSubmitted:(_)=>send(),decoration:const InputDecoration(hintText:'Ex.: Gastei R$ 50 no mercado'))),FilledButton(onPressed:send,child:const Text('Enviar'))]))]);
}
